### ISSUE TITLE
[Remoto] Desenvolvedor na Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [kotlin-br/vagas#14]
**Empresa**
Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. 

**Detalhes da vaga**

Desenvolvedor, atuar com Kotlin e java Java > 8;
Spring MVC; SpringBoot; Programação reativa (Webflux);
Oracle BD; NoSQL BD ;
Monitoria (Splunk, New Relic);
Sólida experiência em AWS;
Versionamento de código utilizando GIT;

**Contratação**
PJ 

**Localidade**
100% remoto

**Se candidatar**
Enviar cv para helen.matos@nexmuv.com.br

**Comment by gustavorribeiro** [comment]
@HelenNexmuv Te enviei um email com o meu CV, aguardo retorno.
